version: '3.1'
services:
  itoken-config:
    restart: always
    image: 10.0.2.27:5000/itoken-config
    container_name: itoken-config
    ports:
      - 8888:8888
    networks:
      - config_network

networks:
  config_network:
